config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :users, only: [:show, :edit, :update]
  
  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]
  # 這裡我們只使用index 這個 template，所以統一 render or redirect 到 index

  def index
    @categories = Category.all

    # 這裡是new or edit 的form所需要的值，如果有url有id就將form帶入edit，沒有就new。
    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

  def create
   @category = Category.new(category_params)
   if @category.save
     flash[:notice] = "category was successfully created"
     redirect_to admin_categories_path
   else
     @categories = Category.all
     render :index
   end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "category was successfully updated"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>
  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>
  <br>
  <div class="form-inline" >
    <!-- [:admin, @category] :admin 是 namespace 的路徑。 -->
    <%= form_for [:admin, @category] do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
      </div>
      <%= f.submit class: "btn btn-primary" %>
      <% if @category.errors.any? %>
        <%= @category.errors.full_messages.to_sentence %>
      <% end %>
    <% end %>
  </div>
  <br>

  <div class="row">

    <div class="col-md-12">

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>
              <!-- 因為我們只有index.html.erb，所以這裡的edit我們加上params[:id]到url裡 -->
              <!-- index 就能判斷是edit or new，而印出對應的form表單 -->
              <%= link_to 'Edit', admin_categories_path(id: category.id) %>
              <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>