config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    # 瀏覽所有餐廳的最新動態
    collection do
      get :feeds
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
    end
  end

  resources :users, only: [:show, :edit, :update]
  
  resources :categories, only: :show
  root "restaurants#index"

  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/add_atrributes_to_user.rb
class AddAtrributesToUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader :image, PhotoUploader
  validates_presence_of :name

  belongs_to :category

  has_many :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader       
  validates_presence_of :name
  
  # 「使用者評論很多餐廳」的多對多關聯
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant



  # admin? 讓我們用來判斷單個user是否有 admin 角色，列如：current_user.admin?
  def admin?
    self.role == "admin"
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  # 這個 Controller 繼承 ApplicationController 所以可以用自己與 Application 的 method
  # 這裡的 namespace controller 在全部繼承這個Base controller 就可以使用這裡的 method了！
  before_action :authenticate_admin

  private

   def authenticate_admin
     unless current_user.admin?
       flash[:alert] = "Not allow!"
       redirect_to root_path
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  # Devise 客製化屬性的使用說明：  https://github.com/plataformatec/devise#strong-parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end
  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end

  # GET restaurants/feeds
  # 會去 render app/views/restuarants/feeds.html.erb
  def feeds
    @recent_restaurants = Restaurant.all.order(created_at: :desc).limit(10)
    @recent_comments = Comment.all.order(created_at: :desc).limit(10)
  end

  # GET restaurants/dashboard
  # 會去 render app/views/restuarants/dashboard.html.erb
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])
    @restaurant.favorites.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  # POST /restaurants/:id/unfavorite
  def unfavorite
    @restaurant = Restaurant.find(params[:id])

    favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    favorite.destroy_all
    redirect_back(fallback_location: root_path)
  end

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

   def show
    @commented_restaurants = @user.restaurants.uniq
   end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro , :avatar)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_restaurant_img(img, css_class = "img-responsive center-block")
    for img_id in 0..18
      include_path = '/'+img_id.to_s+'.jpg'
      return image_tag(('/seed_img'+include_path), class: css_class) if image_path(img).include?(include_path)
    end
    '<span class="glyphicon glyphicon-picture"></span>[沒有圖片]'.html_safe
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- 導覽列 -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= show_restaurant_img(restaurant.image) %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %><p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
      </div>
    </div>
  </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>